name: deepscams
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - boost=1.68.0
  - boost-cpp=1.68.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2019.11.28
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - icu=58.2
  - intel-openmp=2022.0.0
  - jpeg=9d
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libglib=2.68.4
  - libiconv=1.16
  - liblapack=3.8.0
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp-base=1.2.2
  - libxml2=2.9.9
  - lz4-c=1.9.3
  - mkl=2019.4
  - ncurses=6.3
  - numpy=1.11.3
  - numpy-base=1.11.3
  - olefile=0.46
  - pandas=0.19.2
  - pcre=8.45
  - pillow=6.2.1
  - pip=19.3.1
  - pixman=0.38.0
  - pycairo=1.18.2
  - python=2.7.18
  - python-dateutil=2.8.1
  - python_abi=2.7
  - pytz=2019.3
  - rdkit=2018.09.3
  - readline=8.1.2
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - setuptools=44.0.0
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
